name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_agregar
      id: test_agregar
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_agregar
        setup-command: pip install pytest
        command: pytest test_agregar.py
        timeout: 10
        max-score: 45
    - name: test_mostrar
      id: test_mostrar
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_mostrar
        setup-command: pip install pytest
        command: pytest test_mostrar.py
        timeout: 10
        max-score: 45
    - name: test_salir
      id: test_salir
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_salir
        setup-command: pip install pytest
        command: pytest test_salir.py
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_AGREGAR_RESULTS: "${{steps.test_agregar.outputs.result}}"
        TEST_MOSTRAR_RESULTS: "${{steps.test_mostrar.outputs.result}}"
        TEST_SALIR_RESULTS: "${{steps.test_salir.outputs.result}}"
      with:
        runners: test_agregar,test_mostrar,test_salir
